### ISSUE TITLE
Test via Jest fails

### ISSUE THREAD

**Issue by takkyuuplayer** [lucaspbordignon/rn-apple-healthkit#29]
Hi, `import` causes syntax error in testing via Jest. Do you have any idea to solve?

## How to reproduce

1. Initialize

```
$ react-native init <ProjectName>
$ cd <ProjectName>
```

2. Confirm test pass

```
$ yarn test
yarn run v1.5.1
$ jest
 PASS  __tests__/App.js
  ✓ renders correctly (105ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.506s
Ran all test suites.
✨  Done in 1.05s.
```

3. Install rn-apple-healthkit

```
$ yarn add rn-apple-healthkit
```

4. Edit App.js to import rn-apple-healthkit

```diff
diff --git a/App.js b/App.js
index dd1d45a..74f4f28 100644
--- a/App.js
+++ b/App.js
@@ -11,6 +11,7 @@ import {
   Text,
   View
 } from 'react-native';
+import AppleHealthKit from 'rn-apple-healthkit';
```

5. Run test again and it fails

```
$ yarn test
yarn run v1.5.1
$ jest
 FAIL  __tests__/App.js
  ● Test suite failed to run

    /Users/takafumi/rn-apple-healthkit/appleHealthKit/node_modules/rn-apple-healthkit/index.js:5
    import { Permissions } from './Constants/Permissions'
    ^^^^^^

    SyntaxError: Unexpected token import

    > 1 | /**
      2 |  * Sample React Native App
      3 |  * https://github.com/facebook/react-native
      4 |  * @flow

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (App.js:1:791)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.726s, estimated 6s
Ran all test suites.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c jest
Directory: /Users/takafumi/rn-apple-healthkit/appleHealthKit
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/takafumi/rn-apple-healthkit/appleHealthKit/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.3
BuildVersion:   17D102
$ node --version
v9.8.0
$ yarn --version
1.5.1
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.54.2
```

**Comment by takkyuuplayer** [comment]
Setting `transformIgnorePatterns` might be able to solve the problem.

> The transformIgnorePatterns option can be used to whitelist or blacklist files from being transformed with babel. Many react-native npm modules unfortunately don't pre-compile their source code before publishing.
>
> https://facebook.github.io/jest/docs/en/tutorial-react-native.html#transformignorepatterns-customization

**Comment by takkyuuplayer** [comment]
Jest test worked after

```diff
diff --git a/package.json b/package.json
index ff35d6f..c7a2533 100644
--- a/package.json
+++ b/package.json
@@ -18,6 +18,7 @@
     "react-test-renderer": "^16.3.0-alpha.1"
   },
   "jest": {
-    "preset": "react-native"
+    "preset": "react-native",
+    "transformIgnorePatterns": []
   }
 }
```

**Comment by dethell** [comment]
In our project we needed to add `'rn-apple-healthkit'` to the `transformIgnorePatterns` array:

`transformIgnorePatterns: ['node_modules/(?!react-native|react-navigation|rn-apple-healthkit)'],`
